### PR TITLE
Update action to node20

### PR DESCRIPTION
**Pull request by takost**
## Description
Node 16 has reached end-of-life on 11 Sep 202.
This PR updates the default runtime to node20, rather then node16.

This is supported on all Actions Runners [v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) or later.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (add or update README or docs)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by yacaovsnc — APPROVED** [review]

**Comment by takost** [comment]
@yacaovsnc Could you please merge this PR and release new versions of the action? I don't have permissions for it 😄

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
this might be the last major action using nodejs20 runtime? (would be great to see this merged soonish, thanks!)

**Comment by Bo98** [comment]
Looks like this might introduce the same problem that has affected many other node20 updates where it hangs for 2 minutes on completion:
image

I explained the issue at https://github.com/ruby/setup-ruby/issues/543#issuecomment-1793608370.

Short of a full fix in https://github.com/actions/toolkit, the workaround used in `restore` could be applied to `save`: https://github.com/actions/cache/commit/f7ebb81a3f195b4fb88dab7c14e2f7aff52045aa, which has also been copy-pasted to actions/setup-node etc.

**Comment by takost** [comment]
@Bo98 thanks for the comment. I applied the workaround, and I am going to review PR with fix in  https://github.com/actions/toolkit

**Comment by MikeMcC399** [comment]
@yacaovsnc 

I did a smoke test using the pre-release version [actions/cache@v4.0.0](https://github.com/actions/cache/releases/tag/v4.0.0) and it worked fine for me. 👍🏻 

What is the plan to make this into an official release `actions/cache@v4`? 

Currently [actions/cache@v3.3.3](https://github.com/actions/cache/releases/tag/v3.3.3) and `actions/cache@v3` as alias tag are marked as `latest`.

**Comment by yacaovsnc** [comment]
👋🏼 @MikeMcC399, thanks for using Cache actions.  I need to update some internal tests with this latest tag and run through them.  If everything works, we should release this today.

**Pull request merged**
