### PR TITLE
Prepare 2.1.1

### PR DESCRIPTION
**Pull request by smorimoto**
#397

### CODE REVIEW

**Comment by smorimoto** [comment]
CC: @aiqiaoy @joshmgross

**Comment by smorimoto** [comment]
@konradpabjan

**Comment by aiqiaoy** [comment]
Working on releasing this now

**Comment by smorimoto** [comment]
Yay 🙂

**Comment by aiqiaoy** [comment]
v2.1.1 is released and v2 tag is moved to v2.1.1 => https://github.com/actions/cache/releases

**Comment by smorimoto** [comment]
Thanks @aiqiaoy!

**Pull request merged**
