### PR TITLE
Add a restore-only option to support pulling without saving a cache entry

### PR DESCRIPTION
**Pull request by n1hility**
Implements #160 

This feature allows a workflow to minimize storage consumption of the cache by allowing jobs to selectively store. As an example, pull requests, which typically do not have shared use of caches they create, since they are isolated, can be excluded from saving using the following expression: 

` restore-only: ${{ github.event_name == 'pull_request' }}
`

### CODE REVIEW

**Comment by n1hility** [comment]
The macOS failure looks environmental. I don't see it when running directly against my repo.

**Comment by dhadka** [comment]
@joshmgross Any idea what's going on with the `npm ci` error on Mac?

```
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="GitHub Package Registry"
```

**Comment by joshmgross** [comment]
Resolved the unrelated `npm ci` issues on Mac (it was an issue with a new rollout of that image)

I'll take a look at this PR next week, if we add a restore-only option then we may want a `save-only` option as well just for parity.

**Comment by n1hility** [comment]
> Resolved the unrelated `npm ci` issues on Mac (it was an issue with a new rollout of that image)
> 
> I'll take a look at this PR next week, if we add a restore-only option then we may want a `save-only` option as well just for parity.

@joshmgross thanks! I added a separate second commit for save-only in case you decide you want it.

**Comment by n1hility** [comment]
FWIW we have been using this change successfully in our environment

**Comment by joshmgross** [comment]
Thanks, @n1hility 

Long term I think we want to add separate `restore-cache` and `save-cache` actions to get full control over this sort of thing. Ideally, that will go with having a separate NPM package (see #55) to share the same core code.

I'll see if I can figure out a timeline for all of that. Adding additional configuration to the main cache action makes it more complicated for new users of the action (see #94) and I think most use cases should be covered by the existing eviction method of deleting the least used cache.

**Comment by n1hility** [comment]
Thanks for the update @joshmgross. For verbosity reasons, I think if you added 2 additional actions, you would find yourself wanting to mix "cache" (save and restore) with "restore-cache" instead of restore-cache + save cache right next to each other, mixed with restore-cache. So ideally all 3 operations could be mixed at will.

I think the more explicit name approach as separate actions improves readability but it does potentially increase verbosity since you can't reuse expressions  within the action itself. To use an example, sharing a workflow between PRs and branches (the common case) requires that I have two code paths, each duplicating the action for  each path, instead of something like restore-only: ${{ blah}}. 

That said I probably favor the readability over some added redundancy. Care would also need to be taken to ensure the versions expressed in the workflow  between the 3 operations are compatible. (e.g. mixing v3 of save with v2 or restore  could lead to issues if the packaging format changed). That's a minor and easily corrected issue though.

**Comment by boredland** [comment]
this sounds very reasonable, is there a reason NOT to merge this PR?

**Comment by n1hility** [comment]
@joshmgross how do you want me to proceed on this? It looks like there is a package now?

**Comment by joshmgross** [comment]
> @joshmgross how do you want me to proceed on this? It looks like there is a package now?

👋  Hey @n1hility, we do have a package now! To fully support this scenario, we'd need to separate actions so that we don't need to rely on the `post-if` in this action for saving the cache. 

I don't have a timeline for when we'd create those separate actions, as there's an additional support burden from maintaining multiple repositories of the same action.

For now, I'm fine with having a `skip-save` option that would only run the `restore` part of this action. We can ignore any `save-only` option since that wouldn't work well with the `post-if`.

**Comment by jeffalder** [comment]
@n1hility This fixes our use-case. Where does this PR stand? Is there any way I can help move this forward?

Fixes #334

**Comment by sakulstra** [comment]
Is there any way to help moving this forward?

**Comment by vsvipul** [comment]
@n1hility  @sakulstra  @jeffalder  @boredland Now that the allowed usage per repo has been bumped up to 10 GB, is this something that still needs to be triaged and to be considered? 
If yes, please let me know about your use cases and how can it be useful for users so that I can take it forward. If not, we can go ahead and close it and consider it in the future if need arises. 

cc/ @joshmgross

**Comment by vsvipul** [comment]
Closing for now. Feel free to reopen if you feel this has a valid use-case now, along with more details.

**Comment by sakulstra** [comment]
@vsvipul at least for me this request was not related to space issues.

It's more a matter of wanting to seed the cache from somewhere, without overwriting it.

**Pull request closed without merging**
