### PR TITLE
Fix broken links to Restore and Save Actions in README.md

### PR DESCRIPTION
**Pull request by knkarthik**
Fix broken links to Restore and Save Actions in README.md

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (add or update README or docs)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by miparnisari** [comment]
please merge this!!

**Comment by muzimuzhi** [comment]
I find these two links works on both
- https://github.com/actions/cache?tab=readme-ov-file and
- https://github.com/actions/cache/blob/main/README.md

@knkarthik Could you point out in which case they are broken?

**Comment by knkarthik** [comment]
@muzimuzhi Oh, that's weird. https://github.com/actions/cache?tab=readme-ov-file#cache-action wasn't working for me.  I will close this PR then 🤷‍♂️ .

**Comment by muzimuzhi** [comment]
@knkarthik Which browser are you using? Maybe the behavior is browser specific.

The markdown snippet
https://github.com/actions/cache/blob/704facf57e6136b1bc63b828d79edcd491f0ee84/README.md?plain=1#L5-L7
is parsed to HTML

```html
<blockquote>
<p dir="auto">Two other actions are available in addition to the primary <code>cache</code> action:</p>
<ul dir="auto">
<li><a href="/actions/cache/blob/main/restore/README.md">Restore action</a></li>
<li><a href="/actions/cache/blob/main/save/README.md">Save action</a></li>
</ul>
</blockquote>
```
where `/actions/cache/blob/main/restore/README.md` and `/actions/cache/blob/main/base/README.md` are both valid relative URLs, see for example [MDN doc for `<a>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#linking_to_relative_urls).

**Comment by miparnisari** [comment]
> @muzimuzhi Oh, that's weird. https://github.com/actions/cache?tab=readme-ov-file#cache-action wasn't working for me. I will close this PR then 🤷‍♂️ .

I swear I had the same issue a few days ago and now it works just fine even though the README hasn't been touched. I don't get it 😆

**Pull request closed without merging**
