### PR TITLE
Use zstd instead of gzip

### PR DESCRIPTION
**Pull request by imbsky**
Closes: #184 #139 
Useful benchmark and explanation: https://github.com/actions/cache/issues/6#issuecomment-551193422

I would like to thank the following people for their help in making this change (in no particular order): @joshmgross @kcgen @hugovk @miketimofeev

### CODE REVIEW

**Comment by imbsky** [comment]
I use my minimal zstd docker image for testing, but we can copy and manage it under the Actions organization, or I can invite you as collaborators. (If you want.)

**Comment by imbsky** [comment]
For now, this seems to be working for us. Thank you so much to the many people who worked so hard for this change.

**Comment by imbsky** [comment]
Oh, maybe running a zstd installation within Actions VM would have been enough?

**Comment by imbsky** [comment]
@joshmgross @dhadka This is ready for review. Please review this when you have time. and I will leave it to you when to merge this.

**Comment by imbsky** [comment]
At first, I thought that there might be some problems for the users using the master branch, but that seems to be no problem.

**Comment by boredland** [comment]
this cuts our caching speed in half, even though its still enormous (400mb node_modules from a yarn mongorepo. 33-50s to download/extract, 40s to copy the node_modules dirs into the right places)

**Comment by imbsky** [comment]
@boredland By the way, this is a bit off-topic, but caching `node_modules` is a bad idea.

**Comment by imbsky** [comment]
and this is a change for the purpose of speed up cache action using zstd, so it's not a topic to discuss here even if the result is still slow.

**Comment by joshmgross** [comment]
Just merged #212, so there are a bunch of merge conflicts.

Additionally, now that we're including `version` in the cache that we create, I think we should support both `tar` and `zstd` and include that information in the version. Self-hosted runners might not have `zstd` installed.

Let me know if you need any help or want me to take over this PR

**Comment by imbsky** [comment]
@joshmgross Well, I wasn't used to the test with Jest and I couldn't write very clean. I don't think there will be much change, so can you push some commits to this branch?

**Comment by boredland** [comment]
Hi, are there any updates? I really like the speed with this.

**Comment by joshmgross** [comment]
@boredland We're still planning on making this change, just need to ensure that we have a good scenario for self-hosted runners that might not have `zstd` installed

**Comment by imbsky** [comment]
This PR is probably never merged. Because @aiqiaoy took over the rest of this PR work from me. Please check the new PR for additional information.

**Comment by imbsky** [comment]
I will keep this PR as a draft until the new PR is merged, but I will close it when it's merged.

**Comment by imbsky** [comment]
This was merged into the master in another PR!

**Pull request closed without merging**
