### PR TITLE
Bump GitHub actions `actions/checkout` and `actions/setup-node`

### PR DESCRIPTION
**Pull request by magnetikonline**
Bumped the following actions:

- https://github.com/actions/checkout/releases/tag/v3.0.0
- https://github.com/actions/setup-node/releases/tag/v3.0.0
- https://github.com/actions/upload-artifact/releases/tag/v3.0.0

### CODE REVIEW

**Comment by magnetikonline** [comment]
Just bumped the Node.js version used to `16.x` and rebased `main` into branch now we've had a major version bump.

cc: @vsvipul

**Comment by magnetikonline** [comment]
Any chance to look at this @vsvipul / @dhadka ?

**Comment by magnetikonline** [comment]
One for you @brcrista ?

**Review by tiwarishub — APPROVED** [review]
Thank you for your contribution. LGTM 🙇

**Comment by magnetikonline** [comment]
> I'll let @actions/actions-cache pick this up since they maintain this now

Thx @brcrista - I'll try to keep my pings to a minimum 😄

**Comment by magnetikonline** [comment]
> Thank you for your contribution. LGTM 🙇

Thx @tiwarishub 👍 Happy to help.

**Pull request merged**
