### PR TITLE
Adding "always-save" flag to make #840 easier

### PR DESCRIPTION
**Pull request by martinheidegger**
The [current recommendation](https://github.com/actions/cache/issues/342#issuecomment-673371329) has been a bit difficult for me to understand _(and it seems i [am not the only one](https://github.com/actions/cache/issues/840)?)_.

In this PR I implemented a `always-save` flag that makes this easier for me to understand.

### CODE REVIEW

**Comment by Bariscankibarcekici** [comment]
thank you very much

**Comment by jacksongoode** [comment]
Hoping this is a major priority!

**Comment by Luc45** [comment]
I desperately need this feature.

My use case:

- I need to access large amounts of data that is hosted in another git repository.
- I clone the repository (if it doesn't exist) or do a git pull, if it exists, essentially keeping my cache up-to-date with the repository.
- With the current implementation, it assumes that the cache is immutable, so I have to invalidate the entire cache every time there's a change in the other repository, essentially running `git clone` on every cache invalidation (I'm using as cache key the commit SHA of HEAD in that repo). The behavior I would like is to have a persistent cache and run `git pull` in it and save the resulting cache, therefore an `always-save` option would work very well for me.

**Comment by ErcinDedeoglu** [comment]
LGTM.

@bishal-pdMSFT are you going to review or give an answer?

**Comment by kotewar** [comment]
We have released two new actions [actions/cache/restore](https://github.com/actions/cache/tree/main/restore) and [actions/cache/save](https://github.com/actions/cache/tree/main/save) that take care of this case as well. You can now choose to run `save` action with condition `if: always()` and it will always save the cache for you for the given key. 

We had released a beta to get user's feedback, discussion post [here](https://github.com/actions/cache/discussions/1020).
And release post [here](https://github.com/actions/cache/discussions/1028).

Closing this as the use case as been implemented.

**Pull request closed without merging**
