### PR TITLE
Add Deno cache example

### PR DESCRIPTION
**Pull request by jheysaav**

### CODE REVIEW

**Comment by vsvipul** [comment]
@jheysaav  Have you tested this on any of your repos? Can you link the workflow run here? Also, the example needs to be linked to README.md as well.

**Comment by jheysaav** [comment]
Yes of course, I have a repo where I have already tried it: [duxtland/framework](https://github.com/duxtland/framework)

**Comment by vsvipul** [comment]
@jheysaav  That looks good. Can you also link the examples to README.md , as done for other examples ? Thanks.

**Comment by jheysaav** [comment]
Done, I have already added the example link in the readme file

**Review by vsvipul — APPROVED** [review]
LGTM. Thank you for contributing.

**Pull request merged**
