### PR TITLE
General Availability release for new restore and save actions

### PR DESCRIPTION
**Pull request by kotewar**
## Description

Releasing beta code to public for accessing new actions - `restore` and `save`

## Motivation and Context

This is being done to make the granular cache control changes available generally

## How Has This Been Tested?

We had a bugbash to test these and have created canary workflows to test these too.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (add or update README or docs)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by bishal-pdMSFT — APPROVED** [review]

**Review by GO-Institute — COMMENTED** [review]
README.md

**Review by Ciornenichii — COMMENTED** [review]
- Ciornenichii stepan billing office manager

**Review by Homeofficebr2029 — COMMENTED** [review]
ja existiam as ferramentas eu só acrescentei algumas

**Comment by navayla777-dotcom** [comment]
## Description

Releasing beta code to public for accessing new actions - `restore` and

**Comment by Regina1973** [comment]
Os meus arquivos estavam todos atualizados e voce os pegou pra vc

**Pull request merged**
