### PR TITLE
Bump prettier from 1.19.1 to 2.0.1

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by imbsky** [comment]
This PR bumps the version of Prettier to 2. Also, with the current Prettier config, it was not possible to format files other than TypeScript, so I changed the config.

**Comment by imbsky** [comment]
and I have changed config values to default values changed by version 2 to respect the default.

**Comment by imbsky** [comment]
`.gitattributes` is required for CI on Windows. See https://github.com/prettier/prettier/issues/7825.

**Comment by joshmgross** [comment]
:wave: Hey @imbsky, thanks for making this change! 

Unfortunately, changes like this are difficult to review as they touch a large number of files (ex `package-lock.json`) and it's hard to verify that all changes were made by prettier instead of a malicious actor. While I don't think you are malicious, it's generally easier to review this sort of change if made by a core-contributor.

Could you file an issue for us to make this upgrade to prettier?

🙇 Thank you again for your support.

**Comment by imbsky** [comment]
No worries! Your opinion makes perfect sense. I opened this because there are some pretty big changes in Prettier 2.0, such as the pitfalls of end of line. (If you are not forcing lf in gitattributes, CI will fail on Windows)

**Pull request closed without merging**
