### PR TITLE
Add Go modules example

### PR DESCRIPTION
**Pull request by crazy-max**
Workflow example: https://github.com/crazy-max/echo-ipfilter/commit/715af2dd90fbf9b9559aa21e6071a4913634c891/checks?check_suite_id=290272723

### CODE REVIEW

**Comment by imbsky** [comment]
Please add this to the top.

```yml
- [Go - Modules](#go---modules)
```

**Comment by crazy-max** [comment]
@imbsky @joshmgross Done
But maybe we could use the [TOC action](https://github.com/marketplace/actions/toc-generator)?

**Comment by imbsky** [comment]
This example is temporary and will be removed in the future.

**Comment by crazy-max** [comment]
@imbsky Understood, you plan to place each example in a dedicated folder maybe?

**Comment by imbsky** [comment]
See #9.

**Pull request merged**
